return {
  ["impatient"] = true,
  ["mappings"] = true,
  ["lsp"] = true,
  ["dap"] = true,
  ["completion"] = true,
  ["snippets"] = true,
  ["formatting"] = true,
  ["autocommands"] = true,
  ["terminal"] = true,
  ["disable_providers"] = true,
  ["disable_builtins"] = true,
  ["interface"] = true,
  ["neovide"] = vim.g.neovide or false,
}
