return {
  laststatus = 3,
  title = true,
  clipboard = "unnamedplus",
  cursorline = true,
  ignorecase = true,
  smartcase = true,
  number = true,
  numberwidth = 1,
  ruler = false,
  fillchars = { eob = " ", fold = " ", foldopen = "", foldsep = " ", foldclose = "" },
  shortmess = vim.opt.shortmess:append("sI"),
  whichwrap = vim.opt.whichwrap:append("<>[]hl"),
  signcolumn = "yes",
  splitbelow = true,
  splitright = true,
  termguicolors = true,
  undofile = true,
  timeoutlen = 400,
  updatetime = 250,
}
