[options]
indent_width = 2

[vimopts]
laststatus = 3
showmode = false
title = true
clipboard = "unnamedplus"
cursorline = true
expandtab = true
smartindent = true
fillchars = { eob = "" }
ignorecase = true
smartcase = true
mouse = "a"
number = true
numberwidth = true
ruler = false
shortmess = "{+=}sI"
whichwrap = "{+=}<>[]hl"
signcolumn = "yes"
splitbelow = true
splitright = true
termguicolors = true
undofile = true
timeoutlen = 400
updatetime = 250
