local M = {}

local colours = {
  primary = "#4895ef",
  red = "#ff7674",
  orange = "#fac898",
  yellow = "#fdec96",
  green = "#90be6d",
  light_green = "#d9ed92",
  teal = "#34a0a4",
  blue = "#779ecb",
  purple = "#c3b1e1",
  pink = "#f0a6ca",
  light_pink = "#ffd1dc",
  grey = "#5b6571",
  light_grey = "#7c8c9c",
}

local background = {
  base = "#21252b",
  tree = "#1b1e23",
  pmenu = "#16191d",
}

local foreground = {
  base = "#e9ecef",
  secondary = "#ced4da",
}

M.theme = {
  colours = colours,
  background = background,
  foreground = foreground,
  git = {
    diff_add = colours.green,
    diff_remove = colours.red,
    diff_change = colours.orange,
  },
  telescope = {
    background = "#16191d",
    results_background = "#16191d",
    preview_background = "#121417",
    selection = "#1a1e23",
  },
  cursor_line = "#262a31",
  visual = "#2a2f37",
  sign_column = colours.grey,
  line_number = colours.light_grey,
  syntax = {
    String = colours.green,
    Character = colours.orange,
    Number = colours.orange,
    Float = colours.orange,
    Boolean = colours.orange,
    Type = colours.light_pink,
    Identifier = colours.red,
    Constant = colours.teal,
    Function = colours.blue,
    Statement = colours.purple,
    PreProc = colours.purple,
    PreCondit = colours.purple,
    Include = colours.purple,
    Keyword = colours.purple,
    Define = colours.purple,
    Typedef = colours.pink,
    Exception = colours.purple,
    Conditional = colours.purple,
    Repeat = colours.purple,
    Macro = colours.red,
    Error = colours.purple,
    Label = colours.purple,
    Special = colours.red,
    SpecialChar = colours.red,
    Operator = colours.purple,
    Title = colours.teal,
    Tag = colours.green,
    Comment = colours.grey,
    Delimiter = colours.light_grey,
    SpecialComment = colours.grey,
    Todo = colours.red,
  },
  treesitter = {
    ["@annotation"] = foreground.base,
    ["@attribute"] = colours.red,
    ["@boolean"] = colours.orange,
    ["@character"] = colours.orange,
    ["@comment"] = colours.grey,
    ["@conditional"] = colours.purple,
    ["@constant"] = colours.orange,
    ["@constant.builtin"] = colours.orange,
    ["@constant.macro"] = colours.orange,
    ["@constructor"] = { fg = colours.yellow },
    ["@error"] = foreground.base,
    ["@exception"] = colours.purple,
    ["@field"] = colours.red,
    ["@float"] = colours.orange,
    ["@function"] = colours.blue,
    ["@function.builtin"] = colours.teal,
    ["@function.macro"] = colours.teal,
    ["@include"] = colours.purple,
    ["@keyword"] = colours.purple,
    ["@keyword.function"] = colours.purple,
    ["@keyword.operator"] = colours.purple,
    ["@label"] = colours.red,
    ["@method"] = colours.blue,
    ["@namespace"] = colours.purple,
    ["@none"] = foreground.base,
    ["@number"] = colours.orange,
    ["@operator"] = foreground.base,
    ["@parameter"] = colours.red,
    ["@parameter.reference"] = foreground.base,
    ["@property"] = colours.red,
    ["@punctuation.delimiter"] = colours.light_grey,
    ["@punctuation.bracket"] = colours.light_grey,
    ["@punctuation.special"] = colours.red,
    ["@repeat"] = colours.purple,
    ["@string"] = colours.green,
    ["@string.regex"] = colours.orange,
    ["@string.escape"] = colours.red,
    ["@symbol"] = colours.teal,
    ["@tag"] = colours.red,
    ["@tag.delimiter"] = colours.red,
    ["@text"] = foreground.base,
    ["@text.strong"] = { fg = foreground.base, bold = true },
    ["@text.emphasis"] = { fg = foreground.base, italic = true },
    ["@text.underline"] = { fg = foreground.base, underline = true },
    ["@text.strike"] = { fg = foreground.base, strikethrough = true },
    ["@text.title"] = { fg = foreground.base, bold = true },
    ["@text.literal"] = colours.green,
    ["@text.uri"] = { fg = colours.teal, underline = true },
    ["@text.math"] = foreground.base,
    ["@text.reference"] = colours.blue,
    ["@text.environment"] = foreground.base,
    ["@text.environment.name"] = foreground.base,
    ["@note"] = foreground.base,
    ["@warning"] = foreground.base,
    ["@danger"] = foreground.base,
    ["@type"] = colours.light_pink,
    ["@type.builtin"] = colours.pink,
    ["@storageclass"] = colours.purple,
    ["@structure"] = colours.purple,
    ["@variable"] = foreground.base,
    ["@variable.builtin"] = colours.red,
  },
}

return M
